name: brew pr-pull

on:
  workflow_run:
    workflows: ["brew test-bot"]
    types:
      - completed

jobs:
  pr-pull:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      checks: read
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git
        uses: Homebrew/actions/git-user-config@main

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |
          if [ -z "$PULL_REQUEST" ]; then
            echo "::error::No pull request found for this workflow run"
            exit 1
          fi
          brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@main
        with:
          branch: main

      - name: Delete branch
        if: github.event.workflow_run.head_repository.full_name == github.repository
        env:
          BRANCH: ${{ github.event.workflow_run.head_branch }}
        run: git push --delete origin "$BRANCH"
